### PR TITLE
Force shebang to python2

### LINKED ISSUE #52: pagekite.py doesn't start if Python 3 is the default Python
Thanks for your tool guys!

On my Linux distro, the first line of `pagekite.py` 

```
#!/usr/bin/python
```

resolves to Python 3 . I think we can change this generated line to

```
#!/usr/bin/env python2
```

This would also allow the use of virtualenv.

What do you guys think?

### PR DESCRIPTION
**Pull request by JohanLorenzo**
It should fix pagekite/PyPagekite#52

What do you think @BjarniRunar ?

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
ping @pagekite

**Comment by pagekite** [comment]
If I recall, /usr/bin/env doesn't work on Mac OS X. I could be wrong, but I do remember trying to use this method and backing off because it failed on one of my targets.

**Comment by JohanLorenzo** [comment]
Per https://apple.stackexchange.com/questions/297533/does-macos-have-usr-bin-env and https://stackoverflow.com/questions/2429511/why-do-people-write-the-usr-bin-env-python-shebang-on-the-first-line-of-a-pyt/2429517#2429517 ,  macOS supports `/usr/bin/env`. Should we get it landed, @pagekite?

**Comment by BjarniRunar** [comment]
No, sorry.

The distros that decided to make python3 the default are the ones at fault here. Making things better on the distros that caused the problem in the first place, at the expense of the ones that kept things stable and functional isn't my idea of a just world. I encourage you to use a distro that actually cares about not breaking things.

If you're interested in some of the background, I've been through this before on another project. The conclusion we came to on Mailpile, was to use /usr/bin/python2.7, as that seemed to have the broadest support: https://github.com/mailpile/Mailpile/pull/1962 - however, this solution doesn't apply to us, as PageKite is trying to support LTS distros like RHEL/CentOS, some of which still ship Python 2.6.

The solution to this will be to drop support for Pythons older than 2.6 and rewrite pagekite.py so it is compatible with 2.6 - 3.x instead of the current compatibility range of 2.2 - 2.7 (it's impossible to have both in one script).

**Pull request closed without merging**
